server:
  port: 8080 # ????? 8080 ??

spring:
  datasource:
    # ???? MySQL?????? school_competition_db
    url: jdbc:mysql://localhost:3306/school_competition_db?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root        # ????????? root?
    password: z236244462 # ????????????????
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true # ?????? SQL??????
    hibernate:
      ddl-auto: update # ???? Java ??????????